name: CycleGAN
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - ca-certificates=2023.7.22
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=2.0.1
  - ipykernel=6.26.0
  - ipython=8.12.0
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.0.11
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - platformdirs=3.11.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python_abi=3.8
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - traitlets=5.13.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - wcwidth=0.2.8
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - click==8.1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - dominate==2.6.0
      - fonttools==4.43.1
      - gitdb==4.0.10
      - gitpython==3.1.37
      - idna==3.4
      - imageio==2.31.6
      - importlib-resources==6.1.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - libtiff==0.4.2+dummy
      - lpips==0.1.4
      - matplotlib==3.7.3
      - networkx==3.1
      - numpy==1.24.4
      - opencv-python==4.5.3.56
      - pathtools==0.1.2
      - pillow==10.0.1
      - promise==2.3
      - protobuf==3.20.3
      - psutil==5.9.5
      - pylibtiff==0.6.1
      - pyparsing==3.1.1
      - pytorch-msssim==1.0.0
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - requests==2.31.0
      - scikit-image==0.21.0
      - scipy==1.9.3
      - sentry-sdk==1.31.0
      - setproctitle==1.3.3
      - shortuuid==1.0.11
      - smmap==5.0.1
      - tifffile==2023.7.10
      - torch==1.8.1+cu111
      - torchaudio==0.8.1
      - torchfile==0.1.0
      - torchvision==0.9.1+cu111
      - tornado==6.3.3
      - tqdm==4.66.2
      - urllib3==2.0.6
      - visdom==0.1.8
      - wandb==0.12.18
      - websocket-client==1.6.3
      - zipp==3.17.0